services:
  # Container DATA (MariaDB)
  data:
    image: mariadb
    container_name: data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: mabase
      MARIADB_USER: monuser
      MARIADB_PASSWORD: password
    volumes:
      - ./src/create.sql:/docker-entrypoint-initdb.d/create.sql:ro
    networks:
      - tp3-network

  # Container SCRIPT (PHP-FPM)
  script:
    build: .
    container_name: script
    volumes:
      - ./src:/app
    networks:
      - tp3-network

  # Container HTTP (Nginx)
  http:
    image: nginx
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tp3-network
    depends_on:
      - script
      - data

networks:
  tp3-network:
    driver: bridge