services:
  data:
    image: mariadb:latest
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  script:
    build: .
    volumes:
      - ./src:/app
    depends_on:
      - data

  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script